name: Build & Deploy Production
run-name: By @${{ github.actor }} - Build & Deploy Production - ${{github.ref_name}} 🔴🚀
env:
  CI_COMMIT_REF_NAME: production

on:
  push:
    tags:
      - '*'

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          arch: amd64

      - name: 🎯 Check out production Branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: 🛩 Run deployer!!
        run: |
          /bin/bash ./scripts/resources/Deployer.sh
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_CODEDEPLOY_APPLICATION: ${{vars.AWS_CODEDEPLOY_APPLICATION}}
          AWS_CODEDEPLOY_DEPLOYMENT_GROUP_PROD: ${{vars.AWS_CODEDEPLOY_DEPLOYMENT_GROUP_PROD}}
          AWS_CODEDEPLOY_S3_BUCKET: ${{vars.AWS_CODEDEPLOY_S3_BUCKET}}
          AWS_DEFAULT_REGION: ${{vars.AWS_DEFAULT_REGION}}

      - name: 📣 Notificar en Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Deploy a Yubus Production con éxito 🚀😁  @${{ github.actor }}"}' $SLACK_WEBHOOK_URL

      - run: echo "🔊 Final Status ${{ job.status }}."
