name: Build & Deploy develop
run-name: By @${{ github.actor }} - Build & Deploy develop 🚀
env:
  CI_COMMIT_REF_NAME: develop

on:
  workflow_dispatch

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          arch: amd64

      - name: 🎯 Check out production-develop Branch
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0

      - name: 🛩 Run deployer!!
        run: |
          /bin/bash ./scripts/resources/Deployer.sh
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_CODEDEPLOY_APPLICATION: ${{vars.AWS_CODEDEPLOY_APPLICATION}}
          AWS_CODEDEPLOY_DEPLOYMENT_GROUP_DEV: ${{vars.AWS_CODEDEPLOY_DEPLOYMENT_GROUP_DEV}}
          AWS_CODEDEPLOY_S3_BUCKET: ${{vars.AWS_CODEDEPLOY_S3_BUCKET}}
          AWS_DEFAULT_REGION: ${{vars.AWS_DEFAULT_REGION}}

      - name: 📣 Notificar en Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Deploy a Yubus Develop con éxito 🚀😁  @${{ github.actor }}"}' $SLACK_WEBHOOK_URL

      - run: echo "🔊 Final Status ${{ job.status }}."
